### PR TITLE
Chore: fix cargo doc warnings

### PR DESCRIPTION
**Pull request by foxpy**

### CODE REVIEW

**Comment by albertandrejev** [comment]
still got warning about `TODO_LINK` in the https://github.com/neutron-org/neutron-contracts/blob/21f712f4efa8dede28e826b725ec5f5e3286dc1e/packages/neutron-sdk/src/interchain_queries/types.rs#L149

**Comment by foxpy** [comment]
> still got warning about `TODO_LINK`

yep and I am not sure what to do about it. I mean at least I have fixed other warnings!

**Comment by albertandrejev** [comment]
I guess you can remove this message from comment and create jira task to prepare documentation about implemented interchain queries and to add this link back

**Comment by foxpy** [comment]
I am 100% sure someone from the team could provide us with a correct link during review.

**Comment by oopcode** [comment]
> I am 100% sure someone from the team could provide us with a correct link during review.

We can remove this line completely.

**Review by oopcode — APPROVED** [review]

**Review by pr0n00gler — APPROVED** [review]

**Pull request merged**
